### ISSUE TITLE
他人のStageで記録時間の開始、終了が押せてしまう

### ISSUE THREAD

**Issue by Yuki014** [Kait-tt/tacowasa#140]
他人のStageにあるタスクの記録時間の開始、終了が押せてしまうのは仕様？バグ？

**Comment by snakazawa** [comment]
その挙動の認識はしています。
バグっぽいけどまぁいいかなって思ってます。
将来的には、上位の権限を持つ人のみが、他人の記録の操作をできるようにするつもりです。
